apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
data:
  db: test
  application: front-end
  nginx.conf: |
    this is nginx
    configmap example
---

apiVersion: v1
kind: Secret
metadata:
  name: db-secret
data:
  dbusername: YWRtaW4=
  dbpassword: YWRtaW5AMTIz