apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-depl
spec:
  replicas: 6
  selector:
    matchLabels:    # The labels here must match what has been defined under metadata
      app: nginx
      type: front-end
  template:
    metadata:
      name: my-first-app
      labels:
        app: nginx         # The label is up to you
        type: front-end    # You define the labels you want to use
    spec:
      containers:    # Define image for the container and container properties
        - name: my-first-app
          image: nginx
          resources:
            requests:   # Initial or minimum size when pod is created
              memory: "64Mi"
              cpu: "250m"
            limits:     # The maximum size of the pod
              memory: "128Mi"
              cpu: "500m"
          
              
           



# Commands
# kubectl get rs,po,deploy
# kubectl rollout history deploy <deployment-name>
# kubectl rollout undo deployment <deploy-name>   (Rolls back to the former deployment)