apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-depl
spec:
  replicas: 2
  selector:
    matchLabels:    # The labels here must match what has been defined under metadata
      app: nginx
      type: front-end
  template:
    metadata:
      name: my-first-app
      labels:
        app: nginx         # The label is up to you
        type: front-end    # You define the labels you want to use
    spec:
      volumes:
        - name: nginx-conf
          configMap:
            name: db-configmap
      containers:    # Define image for the container and container properties
        - name: my-first-app
          image: nginx
          env:
            - name: dbname
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: db
            - name: application
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: application
            - name: db-uname
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: dbusername
            - name: dbpassword
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: dbpassword
          resources:
            requests:   # Initial or minimum size when pod is created
              memory: "64Mi"
              cpu: "250m"
            limits:     # The maximum size of the pod
              memory: "128Mi"
              cpu: "500m"  # If pod tries to exceed this limit, it will fail with OM - Out of memory error
          volumeMounts:
            - name: nginx-conf
              mountPath: /opt/  # The path where you want to file to be copied into
           



# Commands
# kubectl get rs,po,deploy
# kubectl rollout history deploy <deployment-name>
# kubectl rollout undo deployment <deploy-name>   (Rolls back to the former deployment)

# When resources are defined, the pods are called guaranteed pods. It gives priorities to pods during scheduling.
