apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
spec:
  replicas: 2
  selector:
    matchLabels:    # The labels here must match what has been defined under metadata
      app: nginx
      type: front-end
  template:
    metadata:
      name: my-first-app
      labels:
        app: nginx         # The label is up to you
        type: front-end    # You define the labels you want to use
    spec:
      containers:
        - name: my-first-app
          image: nginx:1.10
