apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
spec:
  type: NodePort       
  selector:
    app: nginx
    type: front-end
  ports:
    - name: http-request
      port: 8080          # This is the service object Port
      targetPort: 80    # Target port is the container port
    - name: https-request
      port: 443        # This is the service object Port
      targetPort: 443
      nodePort: 30001   # This is a port created on the Node, can be likened to Host port




# This is used to access application from outside the cluster. 
# It creates a port in the Node and links it to the ClusterIP before sending to the Pod